name: window_activator
description: A simple plugin for macos to modify the window status.
            Supports window activation (bring to front), as well as
            miniaturization.
version: 0.1.0+1
homepage: https://github.com/wilsonowilson/window_activator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowActivatorPlugin